package model;

public interface Constants {
    int LOGIN_ACTIVITY_REQUEST_CODE = 0;
    int REGISTER_ACTIVITY_REQUEST_CODE = 1;
    int MENU_ACTIVITY_REQUEST_CODE = 2;
    int LIST_RANKS_ACTIVITY_REQUEST_CODE = 0;
    int CREATE_RANK_ACTIVITY_REQUEST_CODE = 1;
    int VOTE_ACTIVITY_REQUEST_CODE = 2;
    int VIEW_RANK_ACTIVITY_REQUEST_CODE = 3;
}
